### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by codemonkeybulucck** [sunweiliang/NeteaseMusicCrack#4]
你好，我想问一下如果不更改BundleID的话我用自己的开发者账号根本无法运行到真机上面，如果更改了BundleID的话可以安装成功，但是没有网络。请问应该怎么做？

**Comment by sunweiliang** [comment]
自己配置一个通用证书。

**Comment by codemonkeybulucck** [comment]
好吧，谢谢，主要是我是个人的账号，无法创建通用的证书。

**Comment by monkeytiny** [comment]
网易云不能改BundleID，否则安装了也没用，所以你先删除已经安装的就行。只能装一个
