### ISSUE TITLE
dyld: Library not loaded: /Library/Frameworks/Cycript.framework/Cycript   Referenced from: /var/containers/Bundle/Application/1967AE2A-4BA0-45BE-8702-697CF12A8B84/WYMusic.app/Frameworks/libWYMusicDylib.dylib   Reason: image not found Message from debugger: Terminated due to signal 6

### ISSUE THREAD

**Issue by tanpengsccd** [sunweiliang/NeteaseMusicCrack#9]
运行时崩溃

dyld: Library not loaded: /Library/Frameworks/Cycript.framework/Cycript
  Referenced from: /var/containers/Bundle/Application/1967AE2A-4BA0-45BE-8702-697CF12A8B84/WYMusic.app/Frameworks/libWYMusicDylib.dylib
  Reason: image not found
Message from debugger: Terminated due to signal 6

**Comment by tanpengsccd** [comment]
iOS  10.3  6
iOS  11.4 SE
均出现问题

**Comment by AloneMonkey** [comment]
去掉链接的Cycript.framework库，另外在动态库的Other link加上 -lcycript

**Comment by tanpengsccd** [comment]
@AloneMonkey 谢谢。看到Other link 里Debug Release 配置不同，我切换成Release就行了。
看样子作者是在调试Cycript，而我的mac 没有作者的配置环境造成的。
